# Build settings
markdown: redcarpet
highlighter: pygments
gems:
  - jemoji
  
# Site settings
title: "Andrew Paradi"
description: > # this means to ignore newlines until "email:"
   A Jekyll theme - Medium inspired

email: me@andrewparadi.com
#blog logo
logo: "/assets/images/df_logo.jpg"
# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'Andrew Paradi'
author: 'Andrew Paradi'
author_image: "/assets/images/author.jpg"

paginate:	10

url: "https://andrewparadi.github.io" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@andrew_paradi'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/andrew_paradi
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

#   - icon:	github
#     url:	https://github.com/andrewparadi
#     desc:	Fork me on github
#     share_url:
#     share_title:
#     share_link:
    
  - icon:	github
    url:	https://github.com/andrewparadi
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
