# Based on https://github.com/dirkfabisch/mediator/ as of Apr 17, 2017

plugins:
  - jemoji
  - jekyll-paginate
  # - jekyll-redirect-from
#  - pygments

# Site settings
title: "Andrew Paradi"
plain_description: Full Stack Engineer
description: # this means to ignore newlines until "email:"
   # Full Stack Engineer Who <i class="fas fa-heart"></i> Data
   Full Stack Engineer

meta_description:
  I code to solve problems with a founder's <strong>hustle</strong> &amp; a designer's <strong>attention to detail</strong>. Software Engineer @ Square Cash, Scalability.

email: me@andrew.fm
logo: "/assets/images/ap_logov4.0t-100c.png"
float_logo: true
cover: "/assets/images/covers/launchpad-c.jpg"
date_format: "%B %e, %Y" # Jun 8, 2017

name: 'Andrew Paradi'
author: 'Andrew Paradi'
author_image_s: "/assets/images/andrew2015-150c.png"
author_image_m: "/assets/images/andrew2015-300c.png"
author_image_l: "/assets/images/andrew2015-600c.png"
author_image: "/assets/images/andrew2015.jpg"
bio_page: "/about"
bio_work: "/project/atomic"
bio_hack: "/experience#Hackathon"
bio_project: "/progress-pebble"
bio_post: "/blog/videostream-how-growth-starts-with-great-customer-support"
bio_video: "https://youtu.be/hfbE7sVbz8k?list=PLmu6fQR8i26VzMOSuUikzqRLT4diEE_AA"
bio_piano: "https://youtu.be/VuBCs_t54DY"
bio_insta: "https://www.instagram.com/"
work_cta: False
work_title: "full stack dev"
work_term: "May 2018"
resume: "/assets/files/AndrewParadiResume.pdf"

google_analytics: UA-15052723-11
google_webmaster_tools: O_pv2dcb2u8RFakuUQcH-TwV5lPeBs6aNXZJY5xYiDs
google_api_key: AIzaSyCZooflwnWhk7gnqyZwoyNhLzAZvxAX484

menu_icon: False
header_menu:
  - title: Experience
    slug: Experience
    url: /experience
    icon: fab fa-road
  - title: Projects
    slug: Project
    url: /projects
    icon: far fa-file-code
  - title: Blog
    slug: Blog
    url: /blog
    icon: fas fa-sticky-note
  - title: About
    slug: about
    url: /about
    icon: fas fa-id-card
  - title: Contact
    desc: Contact
    slug: contact
    url: /contact
    icon: fas fa-envelope
  - title: Resume
    slug: resume
    url: "/assets/files/AndrewParadiResume.pdf"
    icon: fas fa-graduation-cap

show_menu_layouts:
  - default
  - page
  - pattern_header
  - cards
  - card_sections
  - resume

footer_menu:
  - title: All Posts
    url: /404
  - title: Categories
    url: /c
  - title: Tags
    url: /t


url: "//www.andrew.fm" # the base hostname & protocol for your site
baseurl: ""
enforce_ssl:
permalink: /:categories/:title
#used to display twitter cards
twitter_handle: '@andrew_paradi'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

# social icons and sharing options
social:
  - title: LinkedIn
    icon:	fab fa-linkedin
    url:	https://www.linkedin.com/in/andrewparadi
    desc:	Connect with me on LinkedIn
    share_url:
    share_title:
    share_link:
  - title: GitHub
    icon:	fab fa-github
    url:	https://github.com/adrw
    desc:	Fork me on GitHub
    share_url:
    share_title:
    share_link:
  - title: Email
    icon:	fas fa-envelope
    url:	mailto:contact@adrw.ch
    desc:	Email contact@adrw.ch
    share_url:
    share_title:
    share_link:
  - title: Devpost
    icon:	fas fa-code
    url: https://devpost.com/andrewparadi
    desc:	Check out my hacks on Devpost
    share_url:
    share_title:
    share_link:
  - title: AngelList
    icon:	fab fa-angellist
    url:	https://angel.co/andrewparadi
    desc:	Add me on Angel List
    share_url:
    share_title:
    share_link:
  # - title: Twitter
  #   icon:	fab fa-twitter
  #   url:	https://twitter.com/
  #   desc: Follow me on twitter
  #   share_url: http://twitter.com/share
  #   share_title: ?text=
  #   share_link: "&amp;url="
  # - title: Instagram
  #   icon:	fab fa-instagram
  #   url:	https://instagram.com/
  #   desc:	Follow on instagram
  #   share_url:
  #   share_title:
  #   share_link:
  - title: YouTube
    icon:	fab fa-youtube
    url:	https://youtube.com/c/andrewparadi
    desc:	Watch my videos on Youtube
    share_url:
    share_title:
    share_link:
  - title: PGP
    icon:	fas fa-lock
    url:	https://keybase.io/andrewparadi
    desc:	Keybase.io PGP Fingerprint &amp; Public Key
    share_url:
    share_title:
    share_link:
  - title: Resume
    icon:	fas fa-graduation-cap
    url:	/assets/files/AndrewParadiResume.pdf
    desc:	Resume as of Jan 2018
    share_url:
    share_title:
    share_link:

# Collections
collections:
  songs:
    output: False

# Defaults for layouts
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      categories: ""
      author: "Andrew Paradi"
