# By Andrew Paradi | Source at https://github.com/andrewparadi/get-started-with-jekyll

version: '2'
services:

  api:
    image: jekyll/jekyll:pages
    container_name: docker_jekyll
    volumes:
      - ./:/src
    working_dir: /src
    command: bash -c 'jekyll serve -s /src --watch --incremental --safe --profile'
    # command: bash -c 'jekyll build --trace -s /src'
    ports:
      - "4000:4000"
      - "80:4000"
